// Generated by tools/export_phase10_android_gru.py from the frozen Phase 5 checkpoint.
package org.sih26168.idrlogger.engine

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.Base64

internal object FrozenVelocityModelData {
    const val INPUT_SIZE = 10
    const val HIDDEN_SIZE = 32
    const val WINDOW_STEPS = 20
    const val UPDATE_STRIDE_STEPS = 5
    const val PARAMETER_COUNT = 4257
    const val MAXIMUM_RESIDUAL_MPS = 12.0
    const val VALIDATION_RESIDUAL_VARIANCE_MPS2 = 128.78220033954997
    const val CHECKPOINT_SHA256 = "fa2169781f9e499dd87fdd00038a3b4a1326181b31938cec237a7802ae0bb4ec"
    val FEATURE_ORDER = arrayOf("conditioned_forward_acceleration_mps2", "conditioned_left_acceleration_mps2", "gyro_course_rate_radps", "gyro_magnitude_radps", "gravity_magnitude_mps2", "magnetic_magnitude_ut", "motion_accel_rms_mps2", "motion_gyro_rms_radps", "is_likely_stationary", "classical_speed_mps")
    val MEANS = doubleArrayOf(0.016148626804351807, 0.14886894822120667, 0.0054737837053835392, 0.13893903791904449, 9.8065910339355469, 39.560520172119141, 1.36243736743927, 0.1480158269405365, 0.029350277036428452, 8.9912147521972656)
    val STANDARD_DEVIATIONS = doubleArrayOf(0.91943728923797607, 0.86669254302978516, 0.15389712154865265, 0.12364397197961807, 3.8529538869624957e-05, 6.6219344139099121, 0.63204127550125122, 0.11294270306825638, 0.16878636181354523, 10.847951889038086)
    val NORMALIZED_LOWER_BOUNDS = doubleArrayOf(-2.7834877373469209, -3.018146134796079, -3.2325476933367705, -1.0739188691571258, -2.3582800599933322, -1.690717522810312, -1.913860090075904, -1.1900075426767223, -0.17389009005421591, -0.828839852219318)
    val NORMALIZED_UPPER_BOUNDS = doubleArrayOf(2.7859253287628722, 2.9324450102552282, 3.5948380536596845, 3.6801279806796932, 2.0227832356285882, 1.9322060269785746, 3.5399092701603361, 3.7169227694284035, 5.7507589977566731, 4.1428341711745293)
    val GOLDEN_EXPECTED_RESIDUALS = doubleArrayOf(8.2567901611328125, 0.29986661672592163, -0.025409599766135216)
    val GOLDEN_EXPECTED_OOD = doubleArrayOf(254519.01671994, 0.0, 0.076107466155348302)

    private const val ENCODED_FLOAT32_WEIGHTS =
        "LeUIvtVFir4iq5U+ovBnvpdchj6n/Kg+xbicPdbnhz2FLMS8o7y6PuC3kr6ODtw8Ow6lPnruFz7tdN88c22ePR1cRj7keqM+PyzG" +
        "PTxDULxPELO+VbtovqNEOL5u7Ss+pxGUvudlFj9yG8s7KN/VPZ70j72KlCm/E6/yvE6Wc77jlEm+1KFZvRA6Xz5o+EE+s6yRvGW0" +
        "c75Jqte9MdBhPhnPKr4sNYE+qxbmvkK0lD2zhei8Tnk+Ppj+pT10Vhy9QssuvqV3mD2bdUS+cfmMPobXtT7xhIO8zYyrvRagtr40" +
        "XZW++s/PvFVJnr7vTDs+ClSZvjtdaj4KKLE8T6ARPUF1vT3+kiK9Pyd4PryjujyZXCk+oOWyPuWhKL4UuUS9lIxpPSz5kL3iUZ0+" +
        "5QDYPRLN+z1TRgI+R7VJvtg+4D33drM7gGTmve+Ybz523BK7UoHRPWmSoL1c1LG9YYvdPCIQGj5/VjI+R8yPPqSxmj6BMOG8OqI8" +
        "Po91Xb3H0bg6kbnRPM4swr3oKf29qu8VPxyVw70w060+hpsxvsXSmb4Hqsy91uJPPC8TvL4I3Nq+fJ3vPbyrnbyqdFs+znegvAl9" +
        "jbw3vVE+vv6bvE5Td76HqSK+qWBDvmmfub301Cw96EmAvAT/mz5alSI+ABm9PCTw9T11588+tU4APnH9BL6yNgm+fXZCvpCsZL7E" +
        "w0m9/q0Fv2DPPj7y4ni+LCbcva/Nr716Wmu9FPeHvvy77b7nol0+bghePg74Dr5hsV+9YmPgvHsRpL6fjj0+Ri7CvIaPRL5ErvI+" +
        "FFpRPusyoj6BdCM/zTe8PvRvwr3P93++F7KmvQy+6T43rkO+RnaavpSjd76MGKa+54w4PYjrZ74TaIq92VDLvu5jPj1Yvmi8cO4H" +
        "vv//BL7hN7M9gQ+fvgcnzD6n7sW9AkYUPf4njz5DyM6+19wPvV7LrT1nISY+mT5FvlQCt767FyO9c2IsPgI56D0vPog+Yk43Ph5W" +
        "JD3jvE6+p8cSPazPvj5tJ3M+0wYlPsRmGL6bhAm9fc3oPWMgkj5grCI9neSWvno/lz54THA9QSqYvWf7xr2HICU+/tfAPVHILr6/" +
        "tS2+BRQVvkODjzyOyhA+ptZSPsiFpb3BGrm+957CvrZIJb5y3tK6XiKBvrts676kWd+9djysvcIBLz4G6lM+uvP/vpqqQr33vHa+" +
        "CECvven1Rz7jN7W9R1uHvhyHMz5ub9q8A166Pn+Uxb2Ocpa7xFZgvUNgWT4ItGC+VJyjvu8ayzwuK0q9Z0HNPtlQlT6pXMm94gng" +
        "vDSfYL7PNWM8P0ydPRIMJj4n0o49ScVdPsjG4L1drgi+kP7aPsuAQ75cRZC+e3okPl49Hr107AC9gABwvtwB+r01b0y+VsGYvlrv" +
        "2r0Xb0C8KdfZPUp3vz4SpP28vC4Evqt4jb4fbAm9geOHvkFEjb72+4c+W6hPPmheCLzEidS7z5x1Pi0rkb3UKru9Gg8APuESRb4o" +
        "VS4+zWU3vlPuFj4NWPc9t+t3Pkitej7zPGE9xqESvS5d5r67JbM8Eh8PPuHKND5Bh389v2n6ve0D7L0z9+g9JWLLPXzvcr0igsg+" +
        "/miGPTgcJj1vKAq9WnJHPtr3AD7RPSC+FprcvpGilL1acKy+5slDPpPDpD16G/E+IgiYvdfTVD13Fpw+ehwzPnT4hj7/SFQ9ULWC" +
        "PUcKuD54qok+x/IwPtlzB70oDQc/wWGUPWk4i72KdMg9iSaGvmSXk76Ogim/9SCKvS4noz3BeC6+e7U4PZiBJD4bpp2+VfxZvRrP" +
        "O76hiya8bb+Zvvzm473BZ5Q+s3Nivn/V0j7vkXy++TpiPWko4L486m6+mmSgvbyPhb7rzby+OGl+Pr3AOTy3PXY+hesovtvBmj7L" +
        "TDI+9ZhTvi3EiL1yNBC/I5RZPhqmEr3JQOs9NesHPeABFb22wx2+TU+JPkPNgT7J8hm+saUnvwZesD5GfBM++X00vvOSmj7O1mm+" +
        "9ANsPAIDHj4UB8I+kJr8uF11KT7ebhq+KFIjvqH/uL4M75S+JHrIvQtyYz6MeFC+yqy0vqlfGT6zoGq+qClpviCDsD7CWRM+eEIh" +
        "vg0QHD784W49mVTKPU7vVrxX7MC9TuanvHDVoL7jNYM+/WMBvziOXL69gUg94u/9vWx4+j17Bny5tzhBPAlo4L6/JFy7oMAjvnKF" +
        "KT07AWQ+iUAYvsI/zD4kVHm9BgxlPqndjL5gqiS/pP8FvtrvLL6IwJQ+kSPGPhR3mD5ZRrA9ofMYPapPpD791QW9VhAMPtcpRb5n" +
        "vOi++LelPkg9Eb0sH5k+YFkvPlI0vz7xtoM9EMKNvT+Pn76Akte9NCWyPWLulDyGi8I+3BdcvQZiyT5SNvs+rcSlPayES74XTfw+" +
        "wWoWPiJtXzzAt8C9QIzLProtIL5qSFG+Sh6lPr49Sz5mI2g+GK3RvnMWqb6tWIW99F8Evp+vUb57OEM+bZEWPrZVmbypFEG+qxXK" +
        "vjYSar48opC9JQyNvd0IhL5kLYe+SVEmvjVzJz6QhzI+v+XHvvwE0LsICYq+pZoUPtUdJj9ABJQ+XZMePg19yz2cSwA+EyQBPjdG" +
        "Jbx+cVm+8KI1v9xofr4ql0Q+Zg4UPb63/r7/+So+r/obPlNR+L1Y8n49k3AGPQBBDr6qzY++NX4pPhVRIT7fXNo+f1G7vS65ir6R" +
        "pr29sQB5vrsxpL6Q0+C9/SqyvXfjkDxet4k+rNWJPiXaE74BdaO+w5kAvm2j8j3ZuJ65lz2nPqE6QD6pC4I+IDeCvmvGkj1vGWk+" +
        "jn2/vlZ7VD7zYj0+OEhRPWaGBT9uwI28EBeQvl/bpT7TQT89AMIcPR77D76XHFO+aaxLvqtVoD2P3f29etO+PfrMFb7+5Ya9/Fei" +
        "Pq7b9DtTDN89/4+FvTrmsL2QLXC+wjzuPr6pjz5ChSq9Z/ARPs+0Gj7jc+29KE8hvs0GeL0+XV0+5xeZvsWkoj7VMRw+xSWkPvUN" +
        "Ij6I7kS8KnU8PohB2j3O7f4908MWPuKv5TyD9V4+1H2JPSS2ez2l2G0+9t8hvqRaMr5iTQY+T9s8Pk5aoz7q0SK+y9LfvtcUhz5/" +
        "xXO9mmx3vYrwUD4lktq9HJsIOzY/jL7vQEG+j/mxvjKQ576AW38+Lux+PUjsiz6o5WG+7N2Qvf/S0Dz1bYu+/tkRvqu9lL0S1Ua+" +
        "NJ6ZPuy0ib1JFLA9zV+MPmss5D30c/O9pVlzvuREkb6hwpA8mt2ovogpt755x1q/pVdkvukDB78UpVs+KmiJvldyPr4op46+q2tv" +
        "PncZjb7oR6w+/2sOveMxEz5/zo895xiEPY6Kzjzd6WQ95AKPvkZ4zb1zX0E9AoTYvtSU6D0Gd8Q+VVOHvhl/5r7fiRQ8tR4qP5gB" +
        "BD9OkDW+AzgtPtW2Rj7o+OQ9QhUSvQgbGD51sIw+mNEmPFYBAL72k1S9dPsBvZ6mIj2cwOQ9L6cOvpcrML6hO1E8qj5RPUfF2L2P" +
        "MeG9C5aTuw8xzz2yb/89G8YMvtMxPTxFaU2+UYWIPgYh9zyOyXY+HDAyvnRqDj7mLAg+nYI6vdpaXT2krcM7OQr/vICr+L08hl68" +
        "cY0ePgn2ZT35kgA7SfYSvoLSGr5y8nM9JDQQvqtPM74xTMk9HWxFPKh0Dj0EFim9UDMfPo3b172X4ow9xWhbvrSqE74ft9m+p9fE" +
        "Pcv85T0djxS+e0KVvARMjz7p8Fm+wreLPWzvqj1IT5c8S9qHPr8gEz47L3w9oscbPRSPFzwLrO89d/fivX5JTL6W7BE9wWZDvlRt" +
        "pL4DXNI9zjC9vai2DD51vJG9w90JPvTx3b231kK+DFcPPnIRST5wJKC99fdGvssy6jyM3ZI9A9M9PUBUqD1Wfys+foesPQEPkz20" +
        "rQC+KNUOPbmnCz5R2su9P1u5PaHUWr3DAIA9M6vLvdorQz4gvd29WsOzveUmv76YgK29BjXbPeyc8rwljQO+xOWEvhWUBL5uEIg9" +
        "dddBvryk3b2+4oy+7erLvEqJjTx78/I9DbBQPXSEuDszATA+e8cnPvVtrr2CpoM91B8yvhs3hD7aNEa98REkvJPcKL5nEp0+Nr4s" +
        "vhoSrb0w6k29VBMKvlGq5T7hpCC+7T87vI1GgT3guWq+/JUAvlhU+rzf4Yo9/VMFvY/R9j2nc5+9p+m1vXV1gT0XwyI9aaAzPkrA" +
        "BL604368frofvjcfUb6X+HC++IyNPmsi77vch2e+ladTPpHwdT2nUOK9CbwavqF+Ij2GSE6+00WJPm3tbT0U4+I9syuwO8yPDz1q" +
        "9Ra+TihAPvrNGb7FLII78IwkviEw0D2AVRc96UqOvuHqRD626Ew8ASF2vQ/5yLzdJIO8YqjUvSqEHr4cHrq9Dlo2Pf6F4r3r7ti9" +
        "7ZZVvcAyNT5UtfY8EfwhPvBcOr4wPuE954dZvuVLcj61OQY+Y6fLPHbUjTwU1oY9c0YLPokTCL7HXva7M2APvf4ULbzq2Ao++cRo" +
        "vcxmQD6UL5a9RRrDvIsnFr6a7eI9e1EOPmjQHL4Iga49DdxxvhNOFL7Goc69JO+PveWodL3Uadg9tTclPWPYNr5ADgA9HZknPu89" +
        "eL7fLj0+ukVNvcuvLL6i4DQ9aqMvPlwCEj7ShR29iT4dPqJsoj2bI4W+TSndvA0pkT3Lvhc+RrQRPTB8jT10zPO9DE7wvREaR70B" +
        "HuG94bywPSPlmD2nOzS+blMZvBstVr47dli+GL9HvjqWAT6KE029wzScvWmznL0qNwa6AcWtPG6aPT0bqQu9GE0qvsCb0z0xwA6+" +
        "RYjdvYOZi72iLzG86RzSPVgAgzzvoMS9qRR2PtLxDb4vIwM9vIRCPq37KD5Ajj8+dS8ivorv/70GZbq95K/buxATBz5OulU9yeKZ" +
        "ug7+Bz7PVLe8mSPvvImwaz1Ea1e+Acs4PS5wir2Cd6O9eKQ4Pe7s9732WfO901NSPYWZB743hU29XhGVvfBTPb6sFkg+hiiUvG/n" +
        "zjzVVUw993SAPv5TUz5wHqC9TLgbvpBmuT0WEf88tCUAvthJvb2gv2U9ZXxaPa8Qw76LO7G98uMtPG8FRT7wbnK+a2yHvomTd73z" +
        "VM89M5ySvoKo8b19GyK+ERALvjj+pD0QOde9jQRGvhDeNT4ckEY+c+Rgvodaqr6aWqC9+SQ0PuCcTD4XIHY9uKQ/vhF8Ar0j4Q2+" +
        "3TqnPmV7dz6o8Dg+4LgBvn8znr4OFIg+eFetvbm19r6r9Mq+WnONvVV+sL1mcFM+FPKuPZJ6Aj5w5lQ+h/23vty/Qj6KSHw9PD/1" +
        "vXZeMD4ZXoe+8hPuPTNbV7y6lxk+JrLMvdKW5r28C7s7RuHTvnSimT3hCIA+BOqMvbixgr642Ka8cIVUPRkXZL1DLHm+0CIOPpj/" +
        "3L2I4us73q1YvgcdDD6NAsc9xaOrvu8zgz7dQ+E8hrQJvu7+JL3JpiK+D5aFvsR4lb53X7C+Sj2mPsQlvb1UZ/c7DqDvvcqlyT6P" +
        "LaY+V23KPfkq/D3hpyG+B+kFP57FEz4ahBW+riOivr0ZOz5Os1w+5ALqvFYe2j5kKKk+urqRvuv4Kb0Up789hSZpPqp7kTxe0co+" +
        "MABOvkyVt754PYe+drDrPgeFBj+6s1e9f2SKPYsoaT3NWHk9U7SCPHqP1L1eGaQ+ircavpnHWr33D6m9xiE4PpUtIj56oSU+zSQ/" +
        "PuRNeL5kR3u8tnQDvn32Vr4xsoQ9jDiuvl9g+72XBLY+cGjBPSDxtr36jTm9gqjCPS+q7z6ppSE+4QKxPMuYiL4dxwI/99yZvS5x" +
        "HD0p4u09ns0evh/t2D4/VPK9oip5PeKHzD7XbDW+vjmiPlW8sL0Tcs89fHIzPtzinT5h74I+7JqzvokqqTwRVR+9QS3tPtUK7z01" +
        "/Am++BWkvlLJvb6O2YI+fnTiPkghnL1TPZw9ttSwuqTISbzhHH8+Xv9nvoHbtb2Rh2++qwCLvqPHjz4EMXS+mu8MvnDxrb6fRY49" +
        "WLvLvfhxBj55Mta+lvwbPkZCxz2aZZW+R3HivdhphT67B0k+klrLvX5ZfT2voRo9sVk6PqbHh71LWks9q1rBPXn9Ej4elhw+QUyj" +
        "vtq5hj5y8Gu+RjH+PVlxFj7oSq6+RKNqvt/p+L5EEJe94wh2PQhEer48YdK9kjBTvmZBjT6z5Ac9djQwvhLvp70rNmE9A5H5PldZ" +
        "Ub3CKsY9FnKuPiVw0j2kXEC+nmu1vWzfVD6buJ69iyVbvGfObr7Y+Hm+sPGlvYR/FjyTsXS+H2zRvswVYD4RXoc+hybxvLXvgL78" +
        "GYI+riSjvm7qOL2hBpo9HtpuPnx1Tz2XVom+eiSzPLBavrxQcZW9AHBQPmOJOD78lKS9Dwejvvl7Xz6XK0A+On+BPo2q8L3qdxu+" +
        "Ud94Pf+Jzz6Qzou+YswJvSCC6L2xa829ow1pvdQ5CT69CzI8b3CUvoz3lr0qmRS7H5pLvry5IjypR8e+bQoMvrc8Ub3mMba9m/j0" +
        "vTCM8721MTM+udMovpnjWT6CX/W9fLepPNy3oLuN4sa+Vx6fvW/zJj5VD3w+ZvSqPawk370TiVq+6eG3PjvxEz4C+ps+XbAfvMWo" +
        "DD7gPxM9Vd62vUM5jL01GwW+7OF/PWpLpr09vLO+WDNJvpKQdb7Rig8+g/cyPpCLgT6E7Lm9iVMvvo6mgj7Khxw8OWeEvnqEoL72" +
        "2Ak+gAViPQ+mBj0Bmwc+XWPRvg4vKD5wiN69HcNvvRwDk72iJpQ++Gq/vsHwo75ziuQ+Dov7vQOcWDz2cV6+QgrcPZVAG78LJFc+" +
        "zsYLP5Jcmb3UT1M+A/H8vna5D7zDN9w9UVXOvjzd3L007/29oC/1vmbZXD0FlNK+YMtsvhLxgz4lerW+/eWYPjTPUj0dc0k9td36" +
        "vcpOwT7sSkC7RliiPh4M3z3RSCI+FCIPv6V3L76jPyk/udqvPuM7VL1gq8A+j6wgvljCyb2Fssk+Cyo2vJIV1b7XWja9ZrjavW76" +
        "qDyDIQ++N1/FvWRla73NmIy+VVk/PZGoDL7vID+9w2WdPO20RT3WNoS+I7WlPTUmkj1+CTe96gMKvg20pb72ETy+kvIMPkU9ij0N" +
        "DUy+d9zkPfLtCb7UTIm9aoy7PSTsozzULO+8Xr5fPZkJwD2rWZq+Ed8Ovs75Er6uh/O9Z/ZWvtQGL78TD0O9gmo4P+00tr7tMOe9" +
        "YljzPVTXxDxY2SS+WAlhPjQO877sblS+bHRfPiQSHD4oOPA+CjmFvg/RaD5Thqg+O4GavFT1fb4Ify2+6ia9PqtGQD2u/k87uh1o" +
        "PJMgwz6f8li+bAyUvf0tQL/iDym+ayJdPdX4UDy+SoQ9v4uEPdXrtz0TDr++2+cJPdDhBj/EGu+9g7/6PnIFy75Epgi+st/tPYdZ" +
        "vb3zQyQ/WCOGvrpegbsFlEw+ycsRvkJFXL4JRtE+v7JnPvtI975M7fE9T0LLPuAXKz7BaYE+ouFYPl3DdT5dSJG95QG4PNEt4b1a" +
        "jg0+fLlrPQ6/wT4sTsI8xwQxviGBc73CMHm7LtttPm8qyT2AsKC+sk3svcKODz6tldW+XpFMvk/MqT54V9A9RkNfPXNZFL+ebRS9" +
        "+jh4PN/3iL6elRW9zUR8PQ3horxIoaY+2JkFPr9BGb0OzKu9PsWpvBZ4OT6RXWO+PfjQvLhFxb7p/Ze+oLfpPSRtlL6JluM9wnzl" +
        "vgMXuD2xtv89zws2P/Hzj74jfGW9veYQPhVpR7833qK+AoK1PooD4z5Q/jW+uRziPC3mFr2GH58+7JVBvZ3azz7UMqO+CkpbPp9E" +
        "pz5BK76+LXe7vehdSL6ApbM9NgvfO2/s0r41TpO+5ZkVvpM/kb73I7K+9W2lve7CdL6AFx6+yWiyvjD3F71Cwwi+jiU5O2NLqr6j" +
        "83q+TOtpPnd6sb4YU2i9yXBHPtvjPD63m+69yTb1vvPLKT1HSbY+RQgVPb8mpD51MqU+zpk/vgz3m777mUg+g2H5Pfr8pLzHMiO+" +
        "mQhBPYLwBb4cgiq9KeA5PhSHkT7Q1qE9wGGxvpmBpD2+qKG+kxnTviU9/DxvCpe+PUPrPiFeHz61p6i+oVKnu/plQr5b4Rg/cGMs" +
        "vjXNj73TKWe9zvF4PcC/mL0J4gO+3r+vPtuCw77qDN++TeylPVFTlj3iRwq+ZUV2vt8fqz1C7yU+LZeKPjrSLr6aLza8rmgdPfY4" +
        "Cz/m3cG9gowivjOJmD6pFkw+vIaqvppCsLwGLUs9qb8XPznx2D5/5Vg+hbeJvhEgOL6TpLa+PDStPo8JcT4m9Iy8b9mWvku5Jb5X" +
        "i1U+DSNDvoCJx75e71O9vUUoPoN2nTxov/E+PmllvZfqrD3Mxac++FdBO44/Jz5sMyI+OPt5PlB8W77S15A9Z8oUPfVhXL3TjIq+" +
        "sWfuvivkRz7K4xs/npFxvoShk7084ha+O54DPsS237yndJy+idAoPAKqCT14UDG+9bjjvoeU3D2cMoy+Gimlvb05NL4JbeS9E13V" +
        "vdKIlT66+Hc+EXBvvn0pbT74pNa+fzgyPtzWbz2Xyts+7FmFvcf6vL5QdHA9M3PAPCnZkL7wtxi+G207vhoV5z54gHs+pfyiPqrl" +
        "2r3mYH4+4inLvc4qKT0upLe9A5CXPv95gr5usgy9LeCsPe9zlT0c/lC+XnkzvjvyvL1McwO9kvOFPkQfI758pSE+aAvNPg7cD764" +
        "PzG+vcGSPkdP0D5sH42+qy/yPR/FVj5sm7w7VF8HvwtPOD61BcO9ccqVPge9bD43Txw+i785PRnSPL5jtFW7YhfZveR/Fj1xSVs9" +
        "1jgVv0KY8L7cziI+V+6DPiBGM71wOn8+fhgtPp7Kkj7r4IQ7NRRyPraWyD1rwaI+OdW7Ppsv8zryifU9MAWXPSDc2r0GAhM+uAto" +
        "PlOrYD6cpHQ8GI4GvhuD1L2LwKY++EzEu0PlPT4lY7g9mjvSPBjIybzyAw0+BJALPEx4H75RYK++18aJvlmrmj01wgO7sHhCvitO" +
        "/b3JGFE+THl0OzigSbvRg2o+f5sZvhD3kj1fLyK+xevcPVLjEL5p2re+r7SGPQonkT1vlIG+85gNvsfDUb55Law97Lgnvtc5WL57" +
        "aLE+7GmNvcpI0z2oeLk94WDyPY0gKT7byNg+khKJPlMIXT0Czpi+4FiePR4DMD56eiC+rblYvrKf6r2Dz7o9bT58vMCl472KfSE+" +
        "pRhUPFTPJD5kCjY9EyasPjlgKr5IPts9QG3VvZBsCbiD7Wu854kGvo14crzT1TM+6ETyPZ9VdL1axWA+VVF1Pk5YNL6Ji4299kwA" +
        "v6Fdqr0DTTa+9bGMvmYyU7tfKG++MlASPm0lkz5heac+2obxvIybLD7viyu+LAFkPq2XG74M8Lo8kHkfPnUZIL7x3aU90T1Evte0" +
        "xb6K0Xk94ry2vNQchr1lVec9QYKUvmmlGb5UzBw+Hd+IvNQLkb5mh+Y+546pPv0zFzuJ5Jk9wBwDPqJEmj6AefK9hlwlvqwy2b2U" +
        "IjY8XNsQvjNS2777fEe8fUDrPahujb23T9o8LzVDvwFG1rzncfC9BILUPtqZMb6tSxk+8qlxPpvmgL7sDA09WyGmPmitp75FrRu+" +
        "VePqveqMFj7nNQU+9TcLPlOnJT6ZkAa+jBWOvTUAcL18JcA+cJpvPpE5q741oba++J3YPTboIb0xp8c7z0JDvjKk7L2sO0A+Qx0Z" +
        "PlHeUr53fXM84wBBProsO77AOjY+PpZYPYPIv72/MoK+vuTpvV45jr2+Dtg97jzoPdmN4D2/p5A7kRZnPb/s473xoh48Md39Pakx" +
        "XD7dxJg9IDXVPSPp2z1ZjP47WBCTvpauob5JRmg8muisvmYgQr6DC3m+ew1jPRn/jLujEfY9pGCYPYMyS77N98a9Dh2/vtTfU7yN" +
        "QSG+RWMAv1VtyjtVAlg+uSmuO6vo4j18oMg++VgAP5EpUr33Kie+1haVPsLI7rz+mZY+hlmWvY4C/j7nexq+WDv5PXa7KT1frco+" +
        "nqioPkPoE78am7A+y/e9Pm7S6T3iPwG+JzPCPg8VqL77UNG94JzMvrCfyL4cyJA+rg6QPnsAtz7H3oK6jodFvsccFr6rYIw+kv/U" +
        "vVE0gr7L7BK/0r6kvVIKgD6JhSe+mgDAvuELdz4M00Q+/FCCPbFVn74tdRm9GYOiPhEGkr6aU3K+8EmOPpnxL74US+i9bSB8vo0z" +
        "qj2bXg2+IIe+PpiClz6ko9++mdqIPlPejL5nvWY+RYifPJqFyD5aVyM+gj7DvhPkCj1cJP09siQ0vapUp7yx5Bk9DazBPq9Qgr12" +
        "VIi8q0cQP6RmlD1R+ai82PU1vtfFgD6gUNK9B6ztvsoTkb5s/Qg+QDuPO8avFb5WyyW+ZwEuPlJ/4D2qlAw+8Ap4PT08Lr4qo7M+" +
        "dSZ+vX0YcD2qSTs9QOjwvoB5C71iEhk+NNIJvnpHgj1M0oq+vXiMvsV5yT5hhrM962PCvjKVxT4EAcy9e+DAvSErpD0TXLG+ROX6" +
        "PcbKxr7LW2e+JIdSvh7f+72wIbM9MbvqPZez3D7tj5Q+zSwSviZ3Lj6ewLM+B78vvPALzL0u9WS+GMSZvhEBq73b4uW9ycq6PQhs" +
        "fT5sAbO+gFkgPo0jAD9x5pU+PDXCPtWJqb5LR8u+02pFPc5LHL4alx89za7WvRrfx72Whtq+CplKPqix8j6NKDs/rIizvK10Zr2F" +
        "hKk93/MPPcWjvj3hOMU97b+Dvtcu8TwwXBk/L/KnvWPRjj7no/G8H1p5vd82c75DftG9L2DKPTPOfr4945s9WwZkPjL0fj38+xy+" +
        "ewUhvgdq5L1W24o8BWVBPfqEuj6/CoA+oy29PSs6qD6kcII9T5siPhdCJj4W7yo+03M+vQjf5D0jgYK9f6GyvVLQor7n/ta6Z10t" +
        "vnh+ij5bcYS+LY9wvm8uiT3J81S+757KPQUpWL6rgAQ+X8G+Pk1AeT5RESO++UR6vlD6kr486ZM+f6ntvogbWL+rmyk++/HQPg+W" +
        "yL7b9rs9L4I0vncd0r2LlUU9dpWAPhXlIT25q1o+rQ0pvtnnJ79FwZE9EUBXPhic5jsgGpC+2uHbPj4FJT6mvVg+iLGePdMICb/9" +
        "BKG+u+yuvUs4l75MKTI9Jn5JPpwAcr0mz1G9R6H8O/zUrL4KqKO+lptcPgUdQr64P2e9Y8KAPqBmOD4fLOU9aBMQveIvSz63sLk+" +
        "Gf9bvgkMGj62HY0+3T1pvj20W7vhl7W+7XEFPxcemj4+KKc9Ai+QvdUTCL/WFBC+J+YMPHcWx703LWg+Dn+svi9xG7yq5rI9X2ZC" +
        "PxUgzD1mHbI94si9vpuonb4Ued++yJUzvpHFt72YMUC+kxBWPd6x471Zrxq+I+syPubB5T7ma1W+TDpzPFm6kz7edxA+u26FveNi" +
        "tL7Q710++gvnPaClUT5jZ+S+dy0zPllBcL6ubxE/BKe9PvvyLT/1mny98AGYvSf9JT7g/6w9SzMLPr+rvz46x1E9YRhlPbIcFz/o" +
        "JUa95UDovjC3qj0Xy7G+oexJvHm5x77rrgu+kdWxvTBEt71g4pS93YJYPuGOID8ExqS+balyvgUECTwKwPU9mqN/vl9EzbzxvS4/" +
        "ZMIMvwgNoj4S9Z++AN4SvTgaZLxN+HW9JaHsvZsFPD4NIJg+JryJvMRh9LsE4I8+K+lqPSBCiz2AX20+nOi4PNgyrD2DCGc+QiZ4" +
        "vjkCxTx/08w92FhFPl2MDr/677m7/nqhvsvRFz8Y5y69YJ+SPlDiM77rHn2+w5/Yvf0c6b7qqzW+W7M3vh5LoL3ATx0+j2unPfSa" +
        "076HpVg+R1mBvn+UoLviZvk+pgX5vWgtwb5pudk+h5qAvXMcx768R4O6dBnWPTQpE76G8xW8kIRxPkrw5j7v0pG+3gakPmQ0Uj6U" +
        "Jqg+MMWMvYNKf75Re2M8VAnNvSEVjj5Ztik+akSTPnjYSL5Q4rM9hpLYPMYQpj4/JGG+tMY1PvpR1jxLrbE5l/EjPp+Y27zhfGC+" +
        "f7xVPjGx1z4pSyK+U2xdvsn68r3vQRI+dtqPvvmqcT7a8Ba+cxLDPeCFAb6nuao8S6gLPpAniD6UBes+6n7rPfQIiT2C85a944zp" +
        "PSe0yD2oQaY+8CuIvmXhfz6Zejy+3sUwPoQoxr0h5EK+MRYNPa2XHj5Uuio+i61XvU9RfL7QB8m+LGRIvXlvbT73bvc9RfFWvf2p" +
        "Ar3Dspy9QlfxPcpHRz7nPkg+eleMvto/oj3X6PE98vAoPlcGKr7fqxC9P3iYvheY5b1I4Tw+gwefvn1Bgj74dgm+7MhSPvO+w77W" +
        "Evy934VPvicmlb5DmgS/4u3ZPhfJCT595iG+t0aSvWANab33Yqy+DzBcPmQ9CT90Zpm+AUN8PXcKiz7zV9O+d92TPb4wlD5MyDM9" +
        "7X+nvqciEb7Ez9q+P149PgKpb77L2cq9IfIHvyTaqL7ZCfy8sQxHPXZq2z1/HIg+mjL4voo++jycnAo8EhSyvjcNyr6pIDk/Fyqz" +
        "PoS1Bj35C6q+0SXfvlSPDj6BxQC+p4gsvQwTLr1f+2w+mFeFPte45r0H0U8+s5Q1Px5HnL7XcNm+Vbq0PGMTDD3++AU8p/YLv0Fz" +
        "QT4gbq++ShWVvjIOu76CMgI9b27Pvk3mtj46XSU7CssQP5fIg76MZWq+HKQHvVIpLT6I+xE+sppAPoFvZLx1EKC+9ZcDP5pM3z1H" +
        "S6y+se5hvlwbBb5Ry7I9BacAv/6kuL4aFYQ7IyltvnZjpL6R/Rw+g0o8PvAbLT7q6ce+CljdPZNlfD28Uki+TIzsPch4mb4c3dy+" +
        "lHlPvqfjJb11cym9ru6NPSccwD4b4pS78IyFPgWxGr1B2JW+ilXDPsAxyb5Qlhi/J+c5vk8yiz5JCxO+SVQCPiA9rr0PUH2+JMrV" +
        "vTf5Aj57MZo9UJaLvVeUZj2823K+1y9oPTAz5rwMbAo+nnipvc7vYD1KaRY9CPwuPgou97pBNU4+LUF7PkB/kj42j+K8aHWevmor" +
        "mD4Ns9k9CmucvOhHCT8PSla8QYTSvt96GT4ILUo+hBRCPIMjVr4Erek9x+QJPijVrj0Xqhg9MFCQPrlGSb1LWbU+qFIGPTIzID5D" +
        "TK09LevevmJsir41gMe8G7kdP3SlgDyENRg9B11zvlNBQ7u0rls+PSUyvnhy3D40aiQ97L/ZvKcBCb5XCwC+UVz3PTHetz1azC4/" +
        "cT7zvqo/zT37VJe+bglAPlUK4D7tyNI+46pmPgzrZTwF98W+oEkhPuKl2T4LjJ++ZqwvvkaWqb5lJ0o+EmyIPmLCFD4tEzu+Nuz/" +
        "vfbAYT2N9gk/In+PPgqEz74q0Og8dAMNPl2kLr447Z2+JgakPsb7KT7u5oU+0jfUvtwgDb8X+8g9u/Qjvc/+E73YM2k9J95QvUJW" +
        "vj1d36y96gKYvSwRhz20U+m+K9NOPvO63z6rgcQ+lM91PZDksL7TSp2+4acMP4x46r4JTAi+/00Hvj9ccr7M7NG9eXvtvejo172b" +
        "U8w8qoUnvexdWr7tmao9dsivPo2XCb8zIBc+QMycPYsjGD532rE+G6bfvdW8Ar6ITxs+p+LEvH9zh74oPIW+3ejBPkkNxr1qjom+" +
        "LOs+vsG/krx6YoY+HSOQPuWbfb7MTKK+rc/Ivu0wwT4nBc0+JlgTPqYOEb+o0pO+dvoiPcSwCr4tLcU9zKkBP1tggjzw2o49D1BX" +
        "vg8ECL+HN1++7Lv3PLmGoz4hcUg94WMavbYYYD661bs+MB0jPos+dz6f1Iu83jafvb/6Sj5DZKw9k+nMPYW2Fz4DZHc+CkCfvR2E" +
        "BL6c1qA+SXkFviS9QL5pYxY+9X9dPTRNsL7S67A90J8lPrJIFr31z6A9JY9pPjQg97w4BWK+Jr7Wu+zYxT111BW/gUSbPpJMAD4T" +
        "B/W9H3YQPvHJEz6rPeu+cSy0POCe+D1X7JC9bQ3AvhsHUD4h5Zq8iihvPutmET7rwmg+hPPYvgXd+r536Xi9XVRHvkgHc7yAUNm9" +
        "miLpvcNdcr0ut8y8ublxvjDDo74haoM6be0UvRHWej23uYI9B8CCvp7bIT5nfWM9mxEqPparNr0GWli85ftkPXFJaL0EPOy9YJsF" +
        "vtjrRj4+1ZW+RoDRPbQ6J73lyQS+EMwJveockjwbM2M9qHoCvhwyOj4m6Jk95nCRvcuWjr2jA149MZoBPVRtZz54i26+P66OPs9z" +
        "0L1n1eE9WYtNPX3+Ib0sZVA95/+Gvmzipj5n73M97eSdPYQkPr4ChDy+miBRPnOdeT762Aw7F4tJvhC0mT4AhHo+N+IpvtRVar42" +
        "GHE+qCVMvniorrpoIgY/ZmsHvsOVnT5Ysnw9ir/pPQk/oj6uEyA/4ft2vUWYnb6TQGg+Iip3Pe0Enj7jUPm9plyZvKzBkb7uM+C9" +
        "60yAPnKgv752xBy+jpSDvgwQAL7Msdi+mXNWvh/EWDzxSgm+ENebvXnk7z6TTIw+qk+ovUDlMT5heBy+jhgoPgGslrxNRQY+0YgO" +
        "PvnI575hN/Y+s5C7Pmp5bT4HWw2/ebvdvSn9I74s9RM8b40zvprYyj4z5fI85Do1v0DOhT5y9Gy+/1ExPtc8L7/+ggg+leAiu0tb" +
        "Lj6Z0Vm7RqSfPqeYPj7s59a+Mq6nPX3MtTxK+GA+zyo1v7d8MD4rMYI9txUtPkl79D04vIq+4tMavwjQBr6Br6A9n+y/PuOlHb2Y" +
        "QHA7jRaLvQILR72jPMY9KqFTPj99/b2NEkq+FS3wPQ8Td72idU6+h7y0vZ369T3ru8E8pG8XvoB6gz6m+h8+4bY3vsv1t70NfFo+" +
        "hfEuPiv9MbuImHm+mrlHPXT6jT7Be/Q9ap40vngbFb5JMs2+Z2CavcD+qb1IUII9oKhxvEwhPD5y7Qo+NXU5PvwQpr5w3LU9GV42" +
        "PvprF76GB+O9KNF+vQogw73T4Gi+pUrAPeSW+r0wC8k9OLttPWr+Dz7NzDy+Hk+zPVS9GT55jy6+CJaIvqNHlb6IXce8FQcKvvpA" +
        "mT7bpTm+RwFcPdZN9r1ZY8W+zG+BvhxDWb7xG9m9pG8xPgyPGj4mlD+9kRKRPmlknDwGS5m+KfOAPnDEt76sxZg5b55BPlbxJz72" +
        "hVE+CiutvJNuez0rxc4+kO2hPrEttL54Doo+4oHMvQONpL5JtPA+wQAwvgVk1D5ah5A+HZGvvD8/6r49OYy+cZ9APcJuHL4b+ua9" +
        "Ll+fvossNT7ZCT++UgiDvuvbt73xSKA+D79DvsD+m75aqeW9jhYou9QI5b5GSxw/5VdYPWg4Uj5NeTa9R0IwPZFf9z6iDzg+fXGu" +
        "PrPo172n8Le+cpo0voA8pD6cKRm+lyDxPdm+zz1FFag+OYlyvQSCLr6Sj4o+CzTcvR00Xj7zahO+WbMEPWTII73uXQk+u6GIvWao" +
        "Lj6m3Ig+0qimvb45eL5MllC9NcQ4vcq4Lb7EFQw9lttEvmajjL67t3q+qPDivfpxJL0r7I89jSWPPghskD7qUYQ+Ym3CPOzvrT1w" +
        "PVo8gnVYvdOOoD6ox9O9f17fPdhwWb7Wwtq9xrWJPjlFEL4GB9a+OfPgvkwdwz4EsKk+hCVkPled0L4jXmi+GV1+PRyLRL5c5Ka8" +
        "MziXPsMEWb1Afd++LyAGv8Lw3b4udF8+D8d5PkrUPD5qicq9Lkqku1nQS75qnVY80xNcPh7w57wcJ2a/aYEevhz18r79YgU/YiMk" +
        "PGKclD1P8Cg+VXjwPd0ZPj5AsgI+Y+7RPuri1j2/TVg9bpbAva9umL61E0S+V3Q/vvqsMz7ywh++I4exPmnohb0adaS+6qJ/vpua" +
        "Ab3GGK8+Tai0Pc2Rwb0UIkI+XPiZPv29bL0QxDU9hljZPNkNkD50QKG9y7DYvd5VtLzRvb6+Nz7DPnK1ib4xbno+sraTPfM5Mb58" +
        "eok+g2TbPtMC2767XeW9yhtZvLTRzT7T4rA9dK4SvoO7zr2yYxo9+YvcvepHYD5LxNo+dNkGPihzKb3TzXg+aKbWvrVSSr0N/gq+" +
        "Z3TVvhm17r0bMUY+UvZEvnw/KL3GY+e+0QnavUqVtT14bB6+6JSjPTUHeL6c2vU8ONl1PQPlnD0U2fc6rfutvkdZjj1cF2w+DZSQ" +
        "Pc5v4b1BcKc90cwGPt0Ut7yPizA+DNCLvSQpGD4JtTg9RT4Hvsv5zD2xPjK+vS2IvqT/Cb5i2+696nDxvbtrhj4Dzio+bsELvoET" +
        "Oj4OVjq+BdqgPqkLwr0NYk09vJ1BPj35Pr4+uYA+zwbdPBminbwHoYq+ZhKdvf0gfj5zEpW99wTHvc5qAL41gtI93Zo7vdRC7zxL" +
        "ZIS9La0KPsWQSr496aI9WG0OPmoSOb4l3QI+qPrzu8JLVb16HAq9XYs5PpMhCj4kimQ9qkdXPmj7vbuqHCm90GIWPlptBj+kEKs+" +
        "hY2cvpUnoT5QUKA+Pw8ZviXOKDsNoWU+630LvV91yj2/4M8+6GOJPVb4hL0CtvO+oXMRvFG4UD48bMK+omooPZKOv71lMcG9pCyh" +
        "vk6hZD5ZUuG98rx9PceRyb1gnPI93TdWvTCXPD4iOnI+8ON5PiEZ276Jk3C+JSqUvmSZ5T18Wfc9lWeMvry827zuCjM+FQFVPdaS" +
        "hL1r/KO79Y6zvZauG74D1g8+AqVjvTKN8z1J62y8sxCePtLJHj4BWQM++pWRvNzm771PS4A+2KdHPKR28Dzb0Q++Z6U2vuohlL5b" +
        "J2++BDSDPROj7ztza+K9oH7bvUMFeT56W1k+ChBMPvwjG76+vs4+steEPpN1sr4s2ke+IrnVva/ujzw5UZw+iEbfvTTLMz7oHKS+" +
        "RNUKvkCUEb5UqQ4+x4o6Pg+fYb60iVK+pXPgvbranTzrWl49737JPDJgP74l6ic+BtZpPk9vkj7Kc4m+SdGdvUxvdjtKhME9QaFZ" +
        "vtMHXj6tmJA9eg4qvhzItr24dfw+beTdvUckJj6N3ty9fA+aPJZagz2FzjE+CYe9PsKeYj4rYkO+LpiXPDUD871VSn6+locLPuT0" +
        "5DreeMa99kJ/PgSVZD2TMBA+5WXjvSj+Kz4x5pY89tIcvt/8hz23cIu8eTiVvZgOCb452oY9rNDxvGcJ9b1V4Bk+st0OvSBHQb0o" +
        "4pQ9MptjPkezwr2cRtq9YHmjvMhux70UULs8nnIYPoUR7D0Vyu68/NAjvuLdh7s5PyQ8DgOAPomilTzv4y091wZ7vVmXLD5lrg4+" +
        "AOdaPql5Hb4ZqVC+E47zPa5YDL5e04a9zZYTPdIb972e9Ty8ChwKPnjWaz7B942+BlOjPf6DEb4xJa8+mow+vgbIg75bb40+7bX5" +
        "PXCyL73y7xe+c05kPlwx571Vehe+16W6veWUGz4G5Li8a7DBva0AHj6c87a4TZxwPjSGbT1lJ1w+dlXRPXrip7xD7/u8SJWFvcdG" +
        "Gb3eeDu+bOc+Pry64Tz1Qb49twqqPT3/0b2EGJO+49ALvkU9q71exQU+2K/OPT/BKL4vUwc+KFgQvk8EKj5fzYS+nDM2Ps1H7T2Z" +
        "Gk0+p88LvU1mHD4BMKk92k5Jvi43WT0Moyq+OI88PmzwwzwX6Xg+1BJHPBYQUr3dNjE77GoPPlyknjoaGIc+IgD0vf7Jcj3XBcA9" +
        "75u1PVJKN77iwyq+Ty4IvSBYqj0wsJ4+h82RPSjJ3D2bOzo+d39UvtO7gL4qvuE8sK2EPQHhsD3ph3q+XqQfvQDVUz5YMbG8kHUZ" +
        "PTLRhb4CVSy+JnYGvhbtMD7vGyg9CAIsvmC8oj6SjUu+dJpiPiOcvb0W/b89kQXGPVPrvz0U/pY96jlHvfZZRb5ZPSm+PKYXPjrx" +
        "uL1nNe4+QZpCvq7AhL3mpM++2zPnPXmZqD1IuFg+4ISnPk9bOTxylqG+kJoWvUQIOzukfnG95hJEPVwtBb70DwC+1mTbPI0YOj6s" +
        "FfK9Lu3OvUV0iz2KH8o+S3edPhrwozx0aAg8DWacvnXLJ76rvZ2+z4Clvou2Er4vXdw9Lw59vObubbx0CKw+K/k8vr2vCj77dnW8" +
        "9K4svk4DKT56jwA+SVnougUIDbv6tbA9iw/uvS18cb5I7Rk+ItAZPihn5r1SO7a9cSEfPoWOq70qflk+jiwaPhXH8b1bbmS+ihjw" +
        "vWpm9T28WYM+2+MXvmZASz5Ba78+83SwPmBFmr7iX5w99/XsPSK4F7vIWsI+OVPIvdPGiD3iMvW9J8zUvWFw4zw5toU+7sw+vYF1" +
        "Aj7mvdu8SMwVPThMWr0cMJM9vrjWPrxk8LzsUdi+GeN8vvxZmr03Rp0+Z/EhPXgODT5McD6+nrUev9iauz2ehis8GkQBvknuGz5R" +
        "BLG+g99Cvg3clT2Q2DO+t4ZwvufdyDwhTsc+XHUJPo63sr6M4be+ruWePWCIyjyYN3S9+G50Ppy6cr2c5368CkibvtxkbTvFdKM9" +
        "nsS7vbnxSD0g51O+eRskvnJOAr73nNs8tj8vvqzIAj5zW4y+eNb6vEWtJb4xDYo+usn7vCsRZD6WQr88RzmRvkatZT2aaR2+hytc" +
        "PZ4Xij7iYD0+D/Uxvu4kzb2yu368aL0mPtI+Vb6opQs+dymaPvBjPz2YpYW9KNFePNb1DL4JP4S9T8iuPWK8XD6S/c+9ZO1TvmOU" +
        "zT1v1aI8DjDSuxdWqz5cyPu9xhf2Pc/H27zZBAQ+UNHsvcfomTzZCvK89J+XvgMPSb2maSq+FQobPvthzL6svmY+sVy3PnRJKL14" +
        "8xe+Qi+SPixi8r3Sdc29X+ssPbt4lb4nGC8+hxd3vo+SDT0nora8OlaUPhGVKbsKZ+i9Qyw4vvWW+72cXi++CgrcPTPjMD0SgLG6" +
        "91pUPX90ZL5yOo++e7EGPmXZGL3kmts+y2m3vfvTGb5YiiY9mmFHPYWvUD6H31c+leHZPnQLBb0D7p++RYImvZ/jszw/g5u9m6q8" +
        "vGc4BD5gvfo9ogrhvQc/573F4Pe94HUUPexN0rzKdLc+bxonPui1LzxTWxa+oK1xu8XijT4mWrG+JY1VPs89UL6Ngzo+dq2EPgWH" +
        "6D1KsgW+p3X4POxKQT6NTPC9+w8GPjs20z2wDWY+FIBBvgmh/r1S70o8vlWDvj+6lL7GVFm9bxGlPXO9aT3nQoC9F0yPPdp0yr2I" +
        "epg8+psHPmHOmz4R6gu+44wqvqHl8D3hGSY+gS44vhLgH75ewIA+G6UguxTW5LxOdnK+a2vMO94GNL3NCAQ9rVSMvaerUb16++09" +
        "hTnfPQC5Br64jTa83X0APqAyZr6R+zU83BXXvPX8Lj6iMCi+ao8mPDuYhjsMQQQ+7dYfPXCbcr53ZC4+UzlJvsRwvb3qsTy+5z1m" +
        "PiTCBT7bsqy9isKpPVEsqD4iTU89CNCPvlDddb6i27I93FaXvQVbRj68wZo8WUkTPsQDn73yK7K93nhQvvCKwj5P5yA+ytErvgY5" +
        "Eb02K5K9CyEaPSy8IT58HPU9HWY6vjZLq77vWFI+LDNwvna02j0xboe+0YkxvtjGLD4t9Z293r5NvpGxEbyQGku8SbgDvuFgBb6G" +
        "av+9EbSSPd4n+b1bv4a9ZvpFvnY2G74AX7i9qQBSPkLTD77+YAq9JGnMO5WZKL0ZLyi+kF6jvepiO75pxt69szy+PcYxFT2Mlwi9" +
        "3UWHPTjP6L3bLEc+MqysvcYkR7x0eZW9gbp3vq1UMj6abQI+N9B+vvNKkj275H0+sE7LvRuhiryWUEm++hk6vg9KKz6cSpi9H4nV" +
        "PUhwCD6yayk+CFilu3vVhL0boc893HCovQtoBr4MxOW9MZBgPtcR8DwrZoY89bPHOe06Wr7kCEg9Bgp4ugTJK71JEoq+lOGkvv0A" +
        "172fkRy+7G09PpLrgL3V67Y8qX9cvZtrzj6zBe28u3tTviQI3ryug7G+NHkdvgh2fL241xI+WO55PkbsxLv3Bjs8+ks7vutAiT6z" +
        "Vfm8gUMdvph8FjySXKa7J7yFPK7NyD3lHTu+ErJLPTHpDr3oakE+ldmHvvGYij2gLYW6S40VPoLAhz7Qe1S9WKWbvdpXj70XEku+" +
        "wnCKPfM6Iz1qEz0+mGgJvocelb2v67w+pfUSvQ0eBr44Z/S9euAYvucCtjz0ZGw9Xp1ovqDwFL0r27S9rM0FPVSIEL4ZZlQ+EE2E" +
        "vc2Tc711sCO+0x2lvZHykr0/iV8+80xCPepmcL4EYas9dPq1vVpcCT60huw87A0dPlfCPT0P6dS9tqrJPRdnFz4Btxe8vfIsvqPe" +
        "TD2XfLG9Uu10vmyZKTwJ5uG9Q4Lpvf1QrryfGx09/0MdPa81Fz0HXlk6HDIVPhrwqr3Waaw8SboivqJ1hj7Dw4s+6usAvhpNQz4j" +
        "90W+87Yxvuiq9b3Ddnc+enoQPnfxND7+JXO9PqkYvQZJPr3Tunw+n40Pvpc+QD4/hgS+zm2LPXptez4m6Im91MiBPrQimb5vI1q+" +
        "A7icvd3sBj7pstQ9swUFvpZFBz537zM98LEzPhuPSL6unx4+psh4PXcGAT4qLhG+5jYhvoA1oj5YfE+9WNSDvm60VD45ATs93Rpo" +
        "vuQ7gj6khnQ+NgODvYijUr4YKMy9CSsfPmUTAD64zp48Qz7GPbtD6L2gnjO+QR5NPraNhb7X4Wk+VkLIPU1+X77gF+A9+vL+vaRj" +
        "GD44DBi+0L6MvJV8DLzJRn89F+GnvSgOv70M7Dc8RGjyvV3og7wisn89J7XsPKT9Fj6QoE28h3ycPvaeVDy1D52+FBpovnBrqTwn" +
        "Zgo+HZQ/vqUDLD34rTA8OcGjvuVuXzyc6UU9kscyPhhdWD6gk5c4KOB0vQmwGD31yZy8TK5vvc3jaL02KJE6RgAuPRoFnj7K8BU+" +
        "UNg9vdWKiL0NG8q9y0VSvbaTjT2GL1U+BS7RPKhhoz1oXtk9vI+JvCx04D1EOno8/PaPPhsDsb1GQNS9Vx9SPiiZxr4bpjG+nryB" +
        "voy6hz4tBz0843iavbmzRr2QOEo94Kn8PBYzZb5L+F++rWe3PUG3OT6JOCq+wh9PPch2ujyPrlo+eCSDPmqB0b7MpTG+HchRPVYs" +
        "RD5crdc9wvSfPLStDjxES4m+7Cu8veUXlb5CPlg9+3uWPrTMHD4OMjI91g8BPmLLCr0qJp89ouEnvnOJij7ciAS9v0+gvrTpf770" +
        "w3c+XPxQvm9LcT0/m6y7m2ICPik9Fb6S5dc9oFD6vRDANr5Cn8a8gNUyvRur3bxo1Ti9i4P6PHCe7b2VrMA8etYbvlgyuL0mA2M+" +
        "GqvAPXBbID6/zRM+7GEVPlZRyb0Ovx6+N8DRvSgp8D1bSlU+RLZ/vrB7Cb4frR8+OLbOvNKjBL45MGU9wRkRvgIFZj6za0W+/91L" +
        "PuRKc74M6zK+KQJsPhApc70AMbw+L52du7Dbuj3O+Dm9QKq6vDMmqz4yzAu+hfUovkj4ND7J+CO+uYUzvp4RdL5/1c8+z4O1vmcW" +
        "9T1e7CI+jLCQPhS5Lj0bUNa8ZR2BPgAHnb3fn2O+efqcPWn1Ybxa4ge+bfA8PiWB3b2UIz8+UXuMviGYUj6/6Hu8vOhSvn2Lzj4e" +
        "Aqo+3Vf7Pdm0jj0GgsY9+Y7evHa65D3Uogs+bBGCvoNlwT1bIUs+fhOZvRmGZD5sm6M+IP8ZvaAw3z30foE7J6uHPYekFD6yQbO9" +
        "f/93vh9tFr3UvI+96b3rPCeNV76eZzY+qqckPlQQqr0Ok0q9KGOePALjCj2x/IC93HT/PRyHQT6XTJE+e6w6PqVJN77RY3E+qvGh" +
        "Pk/vNrxlMTI+oYNBPlr9Qz0T2g4+VwoRPNpYbT6nvC0+j+Ibvly7Jz0p9hG+wq2yPq57E75fjLs+URpmvGcOOD6Os1q+o4AyPsfw" +
        "iz754Yo99LSCvW2lRj7y04Q9wRlAPbfuhT38uUA9c6MzPNdwCT5QdBg+s1m4PfJHEb6opVW+JzV5PdQ0Hj2Rq6I9KqmBPTSjLr4b" +
        "il6+/94DPm8VCTzW64093A3Wve2D+bzDq4U9p2soPWGVpzwBXTo+nMQevs+u+b2w3Sw+T2WePbRDTj5DDwS+FO7WPL4jGD7/VpW8" +
        "tqXmveyZVb1opT2+GBNgvY90G70EcLE9w0CuvVLRRT6s/0Q8o9mfvZ614T37iRy9iliyPYeYpD3iuzs+WrikPVZLgDygyhG+CrJD" +
        "PVEA0T0UO5S7DiOwORNYub236oi8TIHvvUU0LD0Taoo9FytEPuaCkD3q0BI8BpaIPTFC+Dtn69m9BBAjPupATj6O7lY9t0pGPWi4" +
        "pb7XyEI+FyiCPkTgIj5jS5A8V4AePsmRqz0jGFc+UtCAPYSCRj4gkXw+SMswvod0Az61FJG8kMOAPu+NOL7GAqA+Hc+HPQE2GL0j" +
        "Fk+8SOU3PFxV1D0H1Zc9DskAPl0USD1XYZi8yWlAvVwzoT6leB894QJFvjw3JD66Sl++a7NhPg8wt728d6C9UNOHvSDdCb5duRg+" +
        "4xGmPaO6Ob5FaOg8ZUsLPht/ub2jr7G9vvANvhCCM72ZGra93mDmvbBj4jya7eW9tGxqPaVNt70Z8zo9JGhQvVSjQT5vF4G9mvEa" +
        "Pv+jwb0Jae28yNOlPfJW7r3W+IC+ECmzvd13VL7Ogui9mQCCPu35g72nZMs9vp5GPsKx+z0+DU6+rTANvikMGL7LTVK+6S0ePjg1" +
        "OTwgj4A+oqgBvrQ2c7zXhqS9sNUzPik+VT5a+5U8UsyXPlZYYT6NPsy9KYFNvpMZlD6NDhO+3S1HvqZ9gL02is+9wNiJPqrHoz0c" +
        "rhk9"

    val WEIGHTS: FloatArray by lazy {
        val bytes = Base64.getDecoder().decode(ENCODED_FLOAT32_WEIGHTS)
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        FloatArray(PARAMETER_COUNT) { buffer.float }
    }
}
