"""Export the frozen Phase 5 GRU into compact pure-Kotlin constants and parity vectors."""

from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path
import sys

import numpy as np
import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from idr.ml.features import FEATURE_ORDER  # noqa: E402
from idr.ml.velocity_model import load_velocity_bundle  # noqa: E402


CHECKPOINT = ROOT / "models/phase5/io_vnbd_s1/velocity_gru.pt"
KOTLIN_OUTPUT = ROOT / "android/app/src/main/java/org/sih26168/idrlogger/engine/FrozenVelocityModelData.kt"
PARITY_OUTPUT = ROOT / "results/phase10/ml_parity_vectors.json"
TENSOR_ORDER = (
    "gru.weight_ih_l0",
    "gru.weight_hh_l0",
    "gru.bias_ih_l0",
    "gru.bias_hh_l0",
    "output.weight",
    "output.bias",
)


def kotlin_array(values: list[float] | tuple[float, ...]) -> str:
    def literal(value: float) -> str:
        text = f"{float(value):.17g}"
        return text if any(marker in text.lower() for marker in (".", "e")) else text + ".0"

    return "doubleArrayOf(" + ", ".join(literal(value) for value in values) + ")"


def kotlin_strings(values: tuple[str, ...]) -> str:
    return "arrayOf(" + ", ".join(json.dumps(value) for value in values) + ")"


def main() -> None:
    bundle = load_velocity_bundle(CHECKPOINT)
    payload = torch.load(CHECKPOINT, map_location="cpu", weights_only=True)
    state = payload["state_dict"]
    flattened = np.concatenate(
        [state[name].detach().cpu().numpy().astype("<f4", copy=False).reshape(-1) for name in TENSOR_ORDER]
    )
    parameter_count = int(sum(int(state[name].numel()) for name in TENSOR_ORDER))
    if parameter_count != 4_257 or len(flattened) != parameter_count:
        raise RuntimeError(f"Unexpected frozen parameter count: {parameter_count}")
    encoded = base64.b64encode(flattened.tobytes()).decode("ascii")
    encoded_lines = "\n".join(f'        "{encoded[index:index + 100]}" +' for index in range(0, len(encoded), 100))
    encoded_lines = encoded_lines.rsplit(" +", 1)[0]

    means = np.asarray(bundle.scaler.means, dtype=np.float32)
    standard_deviations = np.asarray(bundle.scaler.standard_deviations, dtype=np.float32)
    windows = {
        "all_zero_raw_features": np.zeros((bundle.config.window_steps, bundle.config.input_size), dtype=np.float32),
        "training_feature_means": np.tile(means, (bundle.config.window_steps, 1)),
        "bounded_sinusoid": np.stack(
            [means + 0.25 * standard_deviations * np.sin(row + np.arange(bundle.config.input_size)) for row in range(bundle.config.window_steps)]
        ).astype(np.float32),
    }
    vectors = []
    for name, window in windows.items():
        residual, exceedance = bundle.predict_window(window)
        vectors.append(
            {
                "name": name,
                "raw_feature_window": window.astype(float).tolist(),
                "expected_residual_mps": residual,
                "expected_ood_exceedance": exceedance,
            }
        )

    expected_residuals = [float(item["expected_residual_mps"]) for item in vectors]
    expected_ood = [float(item["expected_ood_exceedance"]) for item in vectors]
    scaler_means_f32 = tuple(float(value) for value in np.asarray(bundle.scaler.means, dtype=np.float32))
    scaler_std_f32 = tuple(float(value) for value in np.asarray(bundle.scaler.standard_deviations, dtype=np.float32))
    kotlin = f'''// Generated by tools/export_phase10_android_gru.py from the frozen Phase 5 checkpoint.
package org.sih26168.idrlogger.engine

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.Base64

internal object FrozenVelocityModelData {{
    const val INPUT_SIZE = {bundle.config.input_size}
    const val HIDDEN_SIZE = {bundle.config.hidden_size}
    const val WINDOW_STEPS = {bundle.config.window_steps}
    const val UPDATE_STRIDE_STEPS = {bundle.config.update_stride_steps}
    const val PARAMETER_COUNT = {parameter_count}
    const val MAXIMUM_RESIDUAL_MPS = {bundle.config.maximum_residual_mps}
    const val VALIDATION_RESIDUAL_VARIANCE_MPS2 = {bundle.validation_residual_variance_mps2}
    const val CHECKPOINT_SHA256 = "{hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest()}"
    val FEATURE_ORDER = {kotlin_strings(FEATURE_ORDER)}
    val MEANS = {kotlin_array(scaler_means_f32)}
    val STANDARD_DEVIATIONS = {kotlin_array(scaler_std_f32)}
    val NORMALIZED_LOWER_BOUNDS = {kotlin_array(bundle.scaler.normalized_lower_bounds)}
    val NORMALIZED_UPPER_BOUNDS = {kotlin_array(bundle.scaler.normalized_upper_bounds)}
    val GOLDEN_EXPECTED_RESIDUALS = {kotlin_array(expected_residuals)}
    val GOLDEN_EXPECTED_OOD = {kotlin_array(expected_ood)}

    private const val ENCODED_FLOAT32_WEIGHTS =
{encoded_lines}

    val WEIGHTS: FloatArray by lazy {{
        val bytes = Base64.getDecoder().decode(ENCODED_FLOAT32_WEIGHTS)
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        FloatArray(PARAMETER_COUNT) {{ buffer.float }}
    }}
}}
'''
    KOTLIN_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    KOTLIN_OUTPUT.write_text(kotlin, encoding="utf-8")
    PARITY_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    PARITY_OUTPUT.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "source_checkpoint": str(CHECKPOINT.relative_to(ROOT)).replace("\\", "/"),
                "checkpoint_sha256": hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
                "parameter_count": parameter_count,
                "feature_order": list(FEATURE_ORDER),
                "window_steps": bundle.config.window_steps,
                "gate_order": "PyTorch GRU r,z,n",
                "kotlin_tolerance_residual_mps": 1e-4,
                "kotlin_tolerance_ood": 1e-5,
                "vectors": vectors,
            },
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )
    print(f"Exported {parameter_count} parameters and {len(vectors)} parity windows")


if __name__ == "__main__":
    main()
